package ci;


import com.offbytwo.jenkins.JenkinsServer;
import com.offbytwo.jenkins.model.*;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Map;

public class Main {
	private static final String JENKINS_URI = "http://localhost:8080";
	private static final String USERNAME = "firstAdmin";  //jenkins username
	private static final String PASSWORD = "1191e8798b94ac79434a686b0070a4c956"; //jenkins password generated by token api

	private static final String XML_JOB_CONFIG = "src/main/java/ci/jobi.xml";

	public static void main(String[] args) throws InterruptedException {

/*		System.out.println("creating the job");
		JenkinsJob job = new JenkinsJob("monPipeline", XML_JOB_CONFIG);
		System.out.println("reading the job");
		//System.out.println(job.readJob());
		Thread.sleep(2000);

		System.out.println("building the job");
		System.out.println(job.buildJob());
		Thread.sleep(2000);
		//System.out.println("deleting the job");
		//job.deleteJob();
		Thread.sleep(2000);
		System.out.println("listing the jobs");
		System.out.println(JenkinsJob.listJobs());*/



		try {
			JenkinsServer jenkins = new JenkinsServer(new URI(JENKINS_URI), USERNAME, PASSWORD);
			Map<String, Job> jobs = jenkins.getJobs();
			JobWithDetails jobWithDetails = jobs.get("docker").details();
			//System.out.println(jobWithDetails.getLastSuccessfulBuild().details().getConsoleOutputText());
			List<Build> buildsList = jobWithDetails.getAllBuilds();
			for (Build build : buildsList){
				BuildResult buildResult = build.details().getResult();
				System.out.println(buildResult);
			}
		} catch (URISyntaxException | IOException e) {
			e.printStackTrace();
		}


	}


}
